server:
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-alias: spring
    key-store-password: smhrdproject2
  http2:
    enabled: true
  port: 8443

spring:
  jpa:
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project2?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

  messages:
    basename: validation

  mustache:
    expose-request-attributes: true

  main:
    allow-bean-definition-overriding: true

  mvc:
    static-path-pattern: /static/**

  resources:
    add-mappings: true



